


class Error(Exception):
    pass

class EmptyResultSet(Exception):
    """A db query predicate is impossible."""
    pass


class DatabaseError(Error):
    pass


class DataError(Error):
    pass

class TableError(Error):
    pass

class FilterError(Error):
    pass

class FieldError(Exception):
    pass

class DatabaseErrorWrapper:
    """
    Context manager and decorator that reraises backend-specific db
    exceptions using Django's common wrappers.
    """

    def __init__(self, wrapper):
        """
        wrapper is a db wrapper.

        It must have a Database attribute defining PEP-249 exceptions.
        """
        self.wrapper = wrapper

    def __enter__(self):
        pass

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is None:
            return
        for dj_exc_type in (
                DataError,
                OperationalError,
                IntegrityError,
                InternalError,
                ProgrammingError,
                NotSupportedError,
                DatabaseError,
                InterfaceError,
                Error,
        ):
            db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__)
            if issubclass(exc_type, db_exc_type):
                dj_exc_value = dj_exc_type(*exc_value.args)
                # Only set the 'errors_occurred' flag for errors that may make
                # the connection unusable.
                if dj_exc_type not in (DataError, IntegrityError):
                    self.wrapper.errors_occurred = True
                raise dj_exc_value.with_traceback(traceback) from exc_value

    def __call__(self, func):
        # Note that we are intentionally not using @wraps here for performance
        # reasons. Refs #21109.
        def inner(*args, **kwargs):
            with self:
                return func(*args, **kwargs)
        return inner